# Step1: Import Database objects

from database import init_db, Appointment, get_db


init_db()

# Step3: Create Data Contracts using Pydantic Models
import datetime as dt
from pydantic import BaseModel

class AppointmentRequest(BaseModel):
    patient_name: str
    reason: str
    start_time: dt.datetime

class AppointmentResponse(BaseModel):
    id: int
    patient_name: str
    reason: str | None
    start_time: dt.datetime
    canceled: bool
    created_at: dt.datetime

class CancelAppointmentRequest(BaseModel):
    patient_name: str
    date: dt.date

class CancelAppointmentResponse(BaseModel):
    canceled_count: int

class ListAppointmentRequest(BaseModel):
    date: dt.date

# Step2: Create FastAPI application and endpoints pseudo code

from fastapi import FastAPI, HTTPException, Depends
from sqlalchemy.orm import Session


app = FastAPI()

# schedule appt
@app.post("/schedule_appointment/")
def schedule_appointment(request: AppointmentRequest, db: Session = Depends(get_db)): #this tells FastAPI to create a new database session for this endpoint and pass it in as the db parameter, and then automatically close the session after the request is done
    new_appointment = Appointment( #this is the SQLAlchemy model object, not the Pydantic model, we use the Pydantic model to validate and parse the incoming request data, and then we create an instance of the SQLAlchemy model to save to the database
            patient_name=request.patient_name,
            reason=request.reason,
            start_time=request.start_time,
        )
    db.add(new_appointment)
    db.commit() #this saves the new appointment to the database, and at this point the new_appointment object will have its id and created_at fields populated by the database
    db.refresh(new_appointment) #if users asks for the appointment details right after scheduling, this will ensure we have the id and created_at timestamp generated by the database available to return to the user
    new_appointment_return_obj = AppointmentResponse(
        id = new_appointment.id, #gives the agent our appointment id which is generated by the database
        patient_name= new_appointment.patient_name,
        reason=new_appointment.reason,
        start_time=new_appointment.start_time,
        canceled=new_appointment.canceled,
        created_at=new_appointment.created_at
    )
    return new_appointment_return_obj


# cancel appt
from sqlalchemy import select #this is the new import we need to add to run select queries against the database, we will use this in the cancel and list appointment endpoints
@app.post("/cancel_appointment/")
def cancel_appointment(request: CancelAppointmentRequest, db: Session = Depends(get_db)): #we will use the patient name and date to find all appointments for that patient on that date, and then mark them as canceled in the database   
    
    start_dt = dt.datetime.combine(request.date, dt.time.min)
    end_dt = start_dt + dt.timedelta(days=1) #this gives us the start and end datetime for the given date, so we can find all appointments that start on that date regardless of the time, we will use these in our database query to find the relevant appointments to cancel

    result = db.execute( #this is how we run a select query against the database using SQLAlchemy, we use the select function to build a query that selects from the Appointment table, and then we add where clauses to filter by patient name, start time, and canceled status, this will give us all appointments for that patient on that date that are not already canceled
        select(Appointment)
        .where(Appointment.patient_name == request.patient_name) #this filters the appointments to only those that match the patient name provided in the request
        .where(Appointment.start_time >= start_dt) #this filters the appointments to only those that start on or after the start of the given date
        .where(Appointment.start_time < end_dt) #this filters the appointments to only those that start before the end of the given date, together with the previous where clause this ensures we only get appointments that start on the given date regardless of the time
        .where(Appointment.canceled == False)
    )

    appointments = result.scalars().all()
    if not appointments:
        return HTTPException(status_code=404, detail="No matching appointment for the details found in our system")

    for appointment in appointments:
        appointment.canceled = True
    
    db.commit()
    
    return CancelAppointmentResponse(canceled_count=len(appointments))

# list appt
@app.post("/list_appointments/")
def list_appointments(request: ListAppointmentRequest, db: Session = Depends(get_db)): #this endpoint will return all appointments for a given date, we will use the same start_dt and end_dt logic as the cancel endpoint to find all appointments that start on the given date, and then return them in the response
    
    start_dt = dt.datetime.combine(request.date, dt.time.min)
    end_dt = start_dt + dt.timedelta(days=1)
    
    result = db.execute(
        select(Appointment)
        .where(Appointment.canceled == False)
        .where(Appointment.start_time >= start_dt)
        .where(Appointment.start_time < end_dt) # user ne jis din ke bare mein slot book kiya h we'll only talk about it
        .order_by(Appointment.start_time.asc())
    )
    booked_appointments = []
    for appointment in result.scalars().all():
        appointment_obj = AppointmentResponse(
        id=appointment.id,
        patient_name=appointment.patient_name, #
        reason=appointment.reason,
        start_time=appointment.start_time,
        canceled=appointment.canceled,
        created_at=appointment.created_at
    )
        booked_appointments.append(appointment_obj) #this is  done to   

    return booked_appointments

import uvicorn
if __name__ == "__main__":
    uvicorn.run("backend:app", host="127.0.0.1", port=8501, reload=True)